#!/usr/bin/env bash

set -e

getMyIP() {
  local _ip _line
  while IFS=$': \t' read -a _line ;do
    [ -z "${_line%inet}" ] &&
      _ip=${_line[${#_line[1]}>4?1:2]} &&
      [ "${_ip#127.0.0.1}" ] &&
      echo $_ip &&
      return 0
      done< <(LANG=C /sbin/ifconfig)
}

# build and test run values
PORT=${PORT:-8080}
DOCKER_REGISTRY=docker-de.artifacts.dbccloud.dk
DOCKER_NAME=ess-payara-service
DOCKER_REPOSITORY=${DOCKER_REGISTRY}/${DOCKER_NAME}

# app values
ESS_DB_URL=${ESS_DB_URL:-"${USER}:${USER}@$(getMyIP):5432/ess_db"}
BASES=${BASES:-"bibsys,OLUCWorldCat,ArticleFirst"}
MAX_PAGE_SIZE=${MAX_PAGE_SIZE:-"25"}
FORMATS=${FORMATS:-"netpunkt_standard"}

# base image mandatory values
JAVA_MAX_HEAP_SIZE=${JAVA_MAX_HEAP_SIZE:-2G}
LOG_FORMAT=${LOG_FORMAT:-text}

# Lets color a bit. This is clearly a waste of time... (setup in load function).
_NOCOLOR=
_ERROR_COLOR=
_INFO_COLOR=
function info() {
  echo "$(date +"%T.%N") ${_INFO_COLOR}INFO :${_NOCOLOR}" "$@"
}

function debug() {
  echo "$(date +"%T.%N") DEBUG:" "$@"
}

function error() {
  echo "$(date +"%T.%N") ${_ERROR_COLOR}ERROR:${_NOCOLOR}" "$@"
}

function die() {
  error "$@"
  exit 1
}

# If tty output, lets put some colors on.
if [ -t 1 ] ; then
  _INFO_COLOR=$(tput setaf 2)  # Green
  _ERROR_COLOR=$(tput setaf 1)
  _NOCOLOR=$(tput sgr0)
fi
